// 1. Core Enums (The "LEGO Bricks")
// These are the pre-coded behaviors your Phaser engine will know how to execute.
// You can easily expand these lists as you add more mechanics to the game.

export type MovementStyle =
  | 'chase' // Moves directly toward the nearest player
  | 'flee' // Moves away from players if they get too close
  | 'orbit' // Tries to maintain a specific distance, circling the player
  | 'wander' // Moves randomly, ignoring players
  | 'teleport' // Disappears and reappears at intervals
  | 'stationary'; // Does not move

export type AttackPattern =
  | 'contact_only' // Only damages on physical collision
  | 'single_shot' // Fires one projectile at the target
  | 'burst' // Fires a rapid sequence of projectiles
  | 'spiral' // Fires projectiles in a rotating 360-degree pattern
  | 'mine_dropper' // Leaves stationary hazards on the ground
  | 'charging_laser'; // The existing telegraph-then-fire beam

// NEW: Visual Configuration
// Allows the LLM to construct geometric entities on the fly without needing pre-drawn sprites.
export type ShapePrimitive =
  | 'circle'
  | 'square' // 4-sided
  | 'triangle' // 3-sided
  | 'diamond' // 4-sided, rotated
  | 'pentagon' // 5-sided
  | 'hexagon' // 6-sided
  | 'octagon' // 8-sided
  | 'star'; // Multi-pointed star

export interface VisualConfig {
  shape: ShapePrimitive;
  size: number; // Base radius/width in pixels
  fillColor: string; // Hex code (e.g., "0x330033")
  strokeColor?: string; // Hex code for the outline (e.g., "0xff00ff")
  strokeWidth?: number; // Thickness of the outline in pixels
  glowColor?: string; // Hex code for particle trails or light bloom
  spinSpeed?: number; // Degrees per second (for rotating buzzsaw-like enemies)
}

// 2. Component Configurations
// These give the LLM numerical values to tweak the difficulty of the pre-coded behaviors.

export interface MovementConfig {
  style: MovementStyle;
  speed: number; // Base pixels per second
  orbitRadius?: number; // Only used if style is 'orbit'
  cooldownMs?: number; // Only used for 'teleport' (time between jumps)
}

export interface AttackConfig {
  pattern: AttackPattern;
  damage: number; // How much HP the player loses on hit
  fireRateMs: number; // Time between attacks
  projectileCount?: number; // E.g., for 'burst' or 'spiral'
  projectileSpeed?: number; // Speed of the bullets fired
}

// NEW: Spawner Configuration
// Allows any enemy or boss part to act as a factory for other enemies
export interface SpawnerConfig {
  minionNameRef: string; // Matches the `name` of a StandardEnemySchema generated in the LLM's array
  baseSpawnRateMs: number; // Base time between spawns. Engine speeds this up if fewer minions exist.
  maxActive: number; // Maximum number of minions this spawner can have alive at once
  spawnRadius: number; // Distance from the spawner where minions appear
}

// 3. The Base Schema (Shared properties)

export interface BaseEnemyConfig {
  name: string; // Flavor text generated by the LLM
  visuals: VisualConfig; // Procedural geometry definitions
  maxHp: number;
  scoreValue: number; // Points awarded on kill
}

// 4. Standard Enemy Schema

export interface StandardEnemySchema extends BaseEnemyConfig {
  type: 'standard';
  id: string; // unique id for this enemy
  movement: MovementConfig;
  attack: AttackConfig;
  spawner?: SpawnerConfig; // If defined, this enemy also spawns others while fighting!
}

// NEW: Connection Styles
// Defines how a part attaches to its parent mechanically and visually.
export type ConnectionStyle =
  | 'rigid' // Locked to the offsetX/Y relative to its parent. Rotates with parent.
  | 'tether' // Connected by a flexible energy line. Can be dragged around.
  | 'snake' // Slithers exactly behind the parent's path (centipede style).
  | 'orbit'; // Revolves around the parent at a distance determined by offsets.

export interface ConnectionVisuals {
  color: string; // Hex color of the connecting line/beam (e.g. "0x00ff00")
  thickness: number; // Line width in pixels
  isDashed?: boolean; // Renders as a pulsing/dashed energy line
}

export interface ConnectionConfig {
  parentPartId: string; // The partId this is attached to (usually the 'core', or the previous tail segment)
  style: ConnectionStyle;
  visuals?: ConnectionVisuals; // If omitted, the connection is invisible (floating)
  orbitSpeed?: number; // Used only if style is 'orbit' (degrees per second)
  followDelay?: number; // Used only if style is 'snake' (how many frames/ms behind the parent it follows)
}

// 5. Boss Schema (Multi-Part)
// Bosses are massive entities composed of multiple physical parts.

export interface BossPartConfig extends BaseEnemyConfig {
  partId: string; // Unique ID for this part (e.g., 'core', 'left_shield', 'tail_1')
  isCore: boolean; // If the part with isCore=true dies, the entire boss is defeated
  destructible: boolean; // If false, bullets ping off it (acts as indestructible armor/wall)

  // Layout & Hierarchy
  offsetX: number; // X layout distance from the parent (or boss origin if root)
  offsetY: number; // Y layout distance from the parent (or boss origin if root)
  connection?: ConnectionConfig; // If missing, this part is the root (usually the core)
}

export interface PartPhaseBehavior {
  movement?: MovementConfig; // Optional. If missing, it just rigidly follows the core's movement.
  attack?: AttackConfig; // Optional. Can this specific part shoot?
  spawner?: SpawnerConfig; // Optional. E.g., a "hangar" part that releases swarms
  visualEnrage?: boolean;
  // NEW: Immediate spawn trigger
  burstSpawn?: {
    minionNameRef: string;
    count: number;
    spawnRadius: number;
  };
}

export interface BossPhase {
  // Determines when this phase activates
  trigger: {
    type: 'hp_threshold' | 'parts_destroyed';
    value: number | string[]; // e.g., 0.5 (50% core HP) OR ['left_shield', 'right_shield']
  };

  // The behavior of every part during this phase.
  // Keys MUST match the partIds defined in the BossSchema's parts array.
  partBehaviors: Record<string, PartPhaseBehavior>;
}

export interface BossSchema {
  type: 'boss';
  id: string; // unique id for this boss
  name: string; // Overall name of the encounter (e.g., "The Orbital Leviathan")
  parts: BossPartConfig[]; // All the physical pieces that make up the boss
  phases: BossPhase[]; // The state machine determining how parts behave over time
}

// 6. The Final Export for the LLM
// When prompting the LLM, you ask it to generate an array of these configs for the sector.

export type EnemyConfig = StandardEnemySchema | BossSchema;
